sudo: required
services:
  - docker

before_install:
  - docker build -t qassimov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true qassimov/react-test npm test

after_success:
  - docker build -t qassimov/multi-client ./client
  - docker build -t qassimov/multi-nginx ./nginx
  - docker build -t qassimov/multi-server ./server
  - docker build -t qassimov/multi-worker ./worker
  # Login into Docker hub to push images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push qassimov/multi-client
  - docker push qassimov/multi-nginx
  - docker push qassimov/multi-server
  - docker push qassimov/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-085176424340"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY